spring:
      datasource:
           url: jdbc:mysql://192.168.10.102:3306/tp_music?serverTimezone=Asia/Shanghai&useSSL=false&&allowPublicKeyRetrieval=true
           username: root
           password: zxc123...
           driver-class-name: com.mysql.cj.jdbc.Driver
